### ISSUE TITLE
NMS Android: Upload measurements seems to fail consistently 

### ISSUE THREAD

**Issue by jbonisteel** [ooni/probe-multiplatform#257] opened 2024-11-11 15:41 UTC
Steps to reproduce:

- Go to settings and disable Automatically publish results
- Run some tests
- Tap the upload all options on the tests results overview screen
- See the screenshot for the failure message that I am seeing.

I have tried multiple times and I see that same failure message.  I tried again on iOS and the uploading seemed to work. 

![Screenshot_20241111-103757](https://github.com/user-attachments/assets/4a408b7d-2fbc-41e9-af55-1c7273c698a0)

**Comment by sdsantos** [comment] 2024-11-18 18:12
Can't reproduce the issue currently. Could it have been some temporary issue on the back-end? And maybe when you tried on iOS it way working fine?

**Comment by jbonisteel** [comment] 2024-11-19 12:23
@sdsantos I am still able to reproduce this this morning. I don't think it is a backend issue because it reproduces consistently over multiple days. The steps I am using are still the same from the initial report. Screenshot is from this morning. 
![Screenshot_20241119-072004](https://github.com/user-attachments/assets/cb18b02c-1147-4187-a1a8-d3d764f33713)

**Comment by sdsantos** [comment] 2024-11-20 17:42
@jbonisteel Bottom line is, I thought we were publishing on Firebase `release` versions of the app, pointing to the production back-end, and we weren't. A PR has been merged that fixes that. Builds from tomorrow forward should all be using the production back-end, and manual uploads should work.

**Closed** 2024-11-26 11:41 UTC
Labels: priority/medium
